version: "3.7"
services:
  urlwatch:
    build: ./
    restart: always
    container_name: urlwatch
    volumes:
      - ./config/urls.yaml:/root/.urlwatch/urls.yaml
      - ./config/urlwatch.yaml:/root/.urlwatch/urlwatch.yaml
