version: "3.7"
services:
  urlwatch:
    build: ./
    restart: always
    container_name: urlwatch
    environment:
      # e.g. every 5 minutes
      INTERVAL_CRON: "*/5 * * * *"
    volumes:
      - ./config:/root/.urlwatch/config
